### ISSUE TITLE
Ошибка на миллионной итерации

### ISSUE THREAD

**Issue by dresqd** [dresqd/GA_ASDO#2]
Traceback (most recent call last):
  File "C:\Users\dremo\OneDrive\Рабочий стол\GA_ASDO\main.py", line 140, in <module>
    curout = mex.Start(mainexemp)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dremo\OneDrive\Рабочий стол\GA_ASDO\Raschet.py", line 401, in Start
    self.ListP146.pop([0])
TypeError: 'list' object cannot be interpreted as an integer

**Comment by dresqd** [comment]
Исправлено.
self.ListP146.pop([0]) заменен на self.ListP146.pop([0])
Аналогичные команды в Raschet, содержащие метод pop() заменены с pop([x]) на pop(x)
